name: getAllRepliesToKnownPots
concurrency: get_context

on:
  workflow_dispatch:
  schedule:
     - cron: '3,13,23,33,43,53 * * * *'
     
jobs:
  run:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
      - name: Get latest release
        run: |
          curl -s https://api.github.com/repos/nanos/mastodon_get_replies/releases/latest | jq .zipball_url | xargs wget -O download.zip
          unzip -j download.zip
          mkdir artifacts
          ls -lR
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
         cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v2
        with: 
          name: artifacts
          workflow: get_context.yml
          if_no_artifact_found: warn
          path: artifacts
      - name: Get Directory structure
        run: ls -lR
      - run: python get_context.py --access-token=${{ secrets.ACCESS_TOKEN }} --server=${{ vars.MASTODON_SERVER }} --reply-interval-in-hours=${{ vars.REPLY_INTERVAL_IN_HOURS || 0 }} --home-timeline-length=${{ vars.HOME_TIMELINE_LENGTH || 0 }} --max-followings=${{ vars.MAX_FOLLOWINGS || 0 }} --user=${{ vars.USER }} --max-followers=${{ vars.MAX_FOLLOWERS || 0 }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
